package com.example.blockchain.domain.transaction.builder.validator;

public enum BuildTransactionFormValidationResult {

	SUCCESS,
	GENERAL_ERROR,
	INVALID_SCRIPTS_TYPE,
	INVALID_TRANSACTIONS,
	INVALID_OUTPUT_INDICES,
	INVALID_UNLOCKING_KEY_PAIRS,
	TOO_MANY_INPUTS,
	MISMATCHING_INPUTS_COUNT,
	INVALID_AMOUNTS,
	INVALID_LOCKING_PUBLIC_KEYS,
	INVALID_LOCKING_ADDRESSES,
	TOO_MANY_OUTPUTS,
	MISMATCHING_OUTPUTS_COUNT,
	INVALID_LOCKTIME,
	INVALID_BLOCK_HEIGHT;
}
